name: "test pull request"

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  IMAGE_NAME: "simaofsilva/drone-cli"
  CLI_VERSION: "v1.8.0" # renovate: datasource=github-tags depName=harness/drone-cli
  TAG: "test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          build-args: |
            VERSION=${{ env.CLI_VERSION }}
            ARCH=amd64

      - name: Test image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.TAG }} --version
